spring:
  application:
    name: coztion-spring-ai

  datasource:
    url: jdbc:mysql://localhost:3306/coztion?serverTimezone=UTC&encoding=UTF-8
    username: root
    password: 1q2w3e4r!

cloud:
  gcp:
    project-id: coztion-vertex
    credentials:
      scope: https://www.googleapis.com/auth/cloud-platform
