spring:
  application:
    name: coztion-spring-ai

  datasource:
    url: jdbc:mysql://localhost:3306/coztion?serverTimezone=UTC&encoding=UTF-8
    username: root
    password: 1q2w3e4r!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:migration

cloud:
  gcp:
    project-id: coztion-vertex
    credentials:
      scope: https://www.googleapis.com/auth/cloud-platform
